name: build metabase docker
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd metabase-analise
          git checkout master
          git reset --hard origin/master
          git pull
          git checkout .
          docker build -t metabase-customizado .
          docker run -p 3000:3000 --name metabase-modificado -d metabase-modificado
          docker build -t metabase-self-register -f metabase-self-register/Dockerfile metabase-self-register/
          docker run -p 5027:5025 --name metabase-self-register -d metabase-self-register
